Bookstore: styling
Saadat123456/Bookstore pull request #5
Opened 2022-03-30 19:13 UTC by Saadat123456

You will find all the details of the Bookstore design in [Zeplin](https://zeplin.io/).
- [Login to Zeplin](https://app.zeplin.io/login) (hint: you will find the credentials in the [sneak peek](./sneak_peek.md) of the project).
- Open the project *Bookstore CMS*.
- Use the information detailed in Zeplin to style the website.
- Your final design should match Zeplin's design.

2022-03-30 19:53 UTC, elmar8287 requested changes
Hi, @Saadat123456.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

- No linter issues 👍 
- Nice README file 👍 

## Required Changes ♻️

- [ ] Check the comments under the review.

## Optional suggestions

- Please, try to fix the link to the MIT.md file - it is broken.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 19:53 UTC, elmar8287 commented on src/components/NavMenu.jsx
>              className={({ isActive }) => `${styles['nav-link']} ${(isActive ? styles.selected : '')}`}
- [ ] Please consider that there is nothing shown on the screen when I click the check status button. Kindly fix that.
![2022-03-30 23 34 32](https://user-images.githubusercontent.com/49064106/160917204-f7950dce-dabc-490c-aadc-7537924d2914.gif)

2022-03-30 19:53 UTC, elmar8287 commented on src/App.js
>          <Routes>
- [ ] Please, consider that some points are not cover the requested styling. Here on this screenshot, I have marked some points to be fixed.

1. Try to move and align the section with the header "Bookstore CMS" and links to the right, to be on the same line with the books list 👍 
2. Please, try to insert the profile icon where I marked it, as is shown on the original design.
3. Please, consider fixing the styling of the buttons - they should be without the border and fixed in the needed color.
4. "Books" and "Categories" should be uppercase
5. Please, try to insert a divider between "Comments", "Remove" and "Edit"

>Your design
<img width="1423" alt="Screen Shot 2022-03-30 at 23 27 04" src="https://user-images.githubusercontent.com/49064106/160917764-b025a4ee-f4a7-438a-83c6-05ffde253b14.png">

> The requested styling:
<img width="742" alt="Screen Shot 2022-03-30 at 23 26 51" src="https://user-images.githubusercontent.com/49064106/160917863-aebc5db1-9b93-4a0e-b3b9-6cd65dd2fbdf.png">

2022-03-31 01:07 UTC, BrianSammit approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @Saadat123456, 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-31 01:07 UTC, merged